### ISSUE TITLE
CwC icon bouncing on MacOS

### ISSUE THREAD

**Issue by jmedward** [google/coding-with-chrome#170] opened 2018-06-14 01:44 UTC
I've noticed that the CWC icon keeps bouncing on the my mac dock when I minimize it. Typically the bouncing will continue for 30 seconds or so and eventually stop. However, sometimes it randomly starts bouncing again. When i click on the icon, it opens the CWC window and the icon stops bouncing.

**Comment by MarkusBordihn** [comment] 2018-06-14 07:59
Thanks for the report, seems related to the way Chrome Apps are handling this.
Will be fixed in the next version.

**Comment by MarkusBordihn** [comment] 2018-06-15 15:12
I removed all additional "attention" calls from the source code, but the icon is still bouncing in some rare instances.

This seems to be the expected behavior for Chrome Apps on Mac OSX, so there is not a lot which could done from our side.

**Closed by MarkusBordihn** 2018-06-15 15:12 UTC
Labels: external package, wontfix
